# Azure ML environment definition referencing custom image
# Usage:
#   az ml environment create -f azureml-environment.yml
# Then in job spec: environment: { name: d3-meld-mpi-env, version: 1 }

name: d3-meld-mpi-env
version: 1
image: <ACR_NAME>.azurecr.io/d3-meld-mpi:latest

# Optionally specify conda dependencies if layering on top (not needed if image already contains env)
# conda_file: conda.yaml
