name: d3-meld-2-env
channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.10
  - pip
  - openmm
  # mpi4py will pull in msmpi (Windows) or openmpi (Linux) automatically.
  - mpi4py
  - meld  # Note: runtime scripts attempt editable install from ../meld if present (override with USE_LOCAL_MELD=0)
  - mdtraj
  - biopython
  - numpy
  - scipy
  - parmed
  - cudatoolkit
  - python-dotenv>=1.0
