name: d3-meld-env
channels:
  - conda-forge
  - bioconda

dependencies:
  - python=3.10
  - pip
  - openmm
  # mpi4py will pull in msmpi (Windows) or openmpi (Linux) automatically.
  - mpi4py
  - meld
  - mdtraj
  - biopython
  - numpy
  - scipy
  - parmed
  - cudatoolkit
